### ISSUE TITLE
failure mvn install

### ISSUE THREAD

**Issue by harhogefoo** [nolanlawson/jnameconverter-server#1]
When I executed mvn command below.

```
mvn install
```

But, error has occurred...
This is error message.
```
[ERROR] Failed to execute goal on project jnameconverter-server: Could not resolve dependencies for project com.nolanlawson.jnameconverter.server:jnameconverter-server:war:1.0-SNAPSHOT: Failure to find com.nolanlawson:japanese-name-generator-v3:jar:1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

How do I solve this problem?

To solve this problem, it might do below.

You publish `com.nolanlawson:japanese-name-generator-v3:jar:1.1` to maven
or 
I fetch `com.nolanlawson:japanese-name-generator-v3:jar:1.1` then, setup locally and re-install on my laptop.

Is it correct?

Sorry to ask so elementary. I had never been to use maven.

## Environment
- Apache Maven 3.6.0 
- java version "1.8.0_121"
- macOS mojave 10.14.3

**Comment by nolanlawson** [comment]
You have to `mvn install` this project first: https://github.com/nolanlawson/JapaneseNameConverterRoot/tree/master/JapaneseNameConverter-preprocessing

**Comment by nummindie** [comment]
i got error same this topic

and then i got error when mvn install JapaneseNameConverter-preprocessing

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project japanese-name-generator-v3: Compilation failure: Compilation failure:
[ERROR] error: Source option 5 is no longer supported. Use 7 or later.
[ERROR] error: Target option 5 is no longer supported. Use 7 or later.`

### Environment
- Apache Maven 3.6.1
- Java version "JDK 12"
- Windows 10
